import React from 'react'
import { Title,Middle_div } from '../../../styles'

const Page2 = () => (
  <Middle_div>
    <Title>Special Charecteristics</Title>
    <img src='https://tse2.mm.bing.net/th?id=OIP.K0wBNsIKRhTNf9PaUF2PRQHaE8&pid=Api&P=0&w=228&h=153' width='400' height='250'/>
    <div style={{textAlign:'left',paddingLeft:'100px'}}>
      <h3>Humming</h3>
      <p>A hummingbird is named for the prominent humming sound its wingbeats make while flying and hovering to feed or interact with other hummingbirds.  Humming serves communication purposes by alerting other birds of the arrival of a fellow forager or potential mate.  The humming sound derives from aerodynamic forces generated by both the downstrokes and upstrokes of the rapid wingbeats, causing oscillations and harmonics that evoke an acoustic quality likened to that of a musical instrument.   The humming sound of hummingbirds is unique among flying animals, compared to the whine of mosquitoes, buzz of bees, and 'whoosh' of larger birds.</p>
      <br/>
      <h3>Flight Stability</h3>
      <p>During turbulent airflow conditions created experimentally in a wind tunnel, hummingbirds exhibit stable head positions and orientation when they hover at a feeder.  When wind gusts from the side, hummingbirds compensate by increasing wing-stroke amplitude and stroke plane angle and by varying these parameters asymmetrically between the wings and from one stroke to the next.  They also vary the orientation and enlarge the collective surface area of their tail feathers into the shape of a fan.  While hovering, the visual system of a hummingbird is able to separate apparent motion caused by the movement of the hummingbird itself from motions caused by external sources, such as an approaching predator.  In natural settings full of highly complex background motion, hummingbirds are able to precisely hover in place by rapid coordination of vision with body position.</p>
    </div>
  </Middle_div>
)

export default Page2